name: Vinura CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Build the Docker image
  #     run: docker build . --file Dockerfile --tag vinura:latest

  rspec:
    # needs: build
    runs-on: ubuntu-latest
    container:
      image: ruby:2.6.6

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - uses: borales/actions-yarn@v3.0.0
      with:
        cmd: install
    
    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Gem cache
      id: cache-bundle
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: bundle-${{ hashFiles('**/Gemfile.lock') }}

    - name: Bundle install
      env:
        RAILS_ENV: test
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3 --path vendor/bundle

    - name: Setup DB, Run tests
      env:
        PGHOST: postgres
        PGUSER: postgres
        PGPORT: ${{ job.services.postgres.ports[5432] }}
        RAILS_ENV: test
        EXECJS_RUNTIME: Node
      run: |
        bin/rails db:create db:schema:load
        bundle exec rspec